[package]
name = "capture"
version = "0.1.0"
authors = ["Lincoln de Sousa <lincoln@clarete.li>"]
edition = "2018"

[dependencies]
env_logger = "*"
log = "*"
actix = "0.9"
actix-codec = "0.2.0"

failure = "0.1"
awc = "1.0.1"
futures = "0.3.1"
bytes = "0.5.3"

serde = "1"
serde_derive = "1"
serde_json = "1"