[package]
name = "protocol"
version = "0.1.0"
authors = ["Lincoln de Sousa <lincoln@clarete.li>"]
edition = "2018"

[dependencies]
env_logger = "*"
log = "*"
actix = "0.9"
actix-rt = "1.0"
actix-web = "2.0"
actix-web-actors = "2.0"
toml = "0.5"
serde = "1.0"
serde_derive = "1.0"
