#!/bin/sh

DOMAIN=guinho.home

CERTS=../server/certs/

webpack-dev-server \
    --https \
    --key $CERTS/server.key \
    --cert $CERTS/server.crt \
    --cacert $CERTS/rootCA.pem \
    --host $DOMAIN
